### ISSUE TITLE
[Feature Request] Scanning for codes in background

### ISSUE THREAD

**Issue by timbrueckner** [mintware-de/flutter_barcode_reader#259] opened 2020-06-19 21:10 UTC
We want to use the plugin to scan EAN codes of products rather fast without changing between Flutter UI and camera views.

Is it possible to not switch to the camera view but scanning for barcodes in the background somehow? The plugin could trigger a callback function when a code was scanned successfully.

**Comment by jvieirar** [comment] 2020-06-28 06:28
I'm really interested on having this feature too. It would be really useful to stay in the scanner view and just get a callback with the result. Our idea is to show a popup in the same scanner view.
Thanks!

**Comment by FickleLife** [comment] 2020-06-30 20:49
+1. I’d like to split the screen in two, have the scanner rapidly scanning items above and below have the results show on each successful scan.

**Comment by willyou** [comment] 2020-07-01 02:30
+1, we are very interested on having this feature too!

**Comment by devtronic** [comment] 2020-07-02 23:11
Dupe of #147

**Closed as completed by devtronic** 2020-07-02 23:11 UTC
Labels: Feature

**Comment by timbrueckner** [comment] 2020-07-03 07:43
Sorry for responding late. I think the difference between #147 and this is, that I do NOT want a camera view. I want to stay in the UI of the Flutter application and let the camera scan for codes without switching to a camera view, but maybe I got it wrong. ☕️✌️+1 also for the suggestion of @FickleLife to be able to split the view.
