### ISSUE TITLE
iPad Pro iPadOS 13.2 the window is clipped

### ISSUE THREAD

**Issue by StephanCassel** [mintware-de/flutter_barcode_reader#159] opened 2019-11-06 19:54 UTC
Hi

iPad Pro iPadOS 13.2 the window is clipped, see pic. The scanner works but it doesn't looks good

![Screenshot 2019-11-06 at 20 47 52](https://user-images.githubusercontent.com/5372762/68332530-47281800-00d7-11ea-8b8e-ddef0e6af865.png)

**Comment by terry8204** [comment] 2019-12-27 02:49
Have the same problem, need improve.

**Comment by terry8204** [comment] 2019-12-27 03:27
- (void)showBarcodeView {
    BarcodeScannerViewController *scannerViewController = [[BarcodeScannerViewController alloc] init];
    UINavigationController *navigationController = [[UINavigationController alloc] initWithRootViewController:scannerViewController];
    scannerViewController.delegate = self;
   **scannerViewController.modalPresentationStyle = UIModalPresentationFullScreen;
    navigationController.modalPresentationStyle = UIModalPresentationFullScreen;**
    [self.hostViewController presentViewController:navigationController animated:NO completion:nil];
}

add two lines in the BarcodeScanPlugin.m
scannerViewController.modalPresentationStyle = UIModalPresentationFullScreen;
    navigationController.modalPresentationStyle = UIModalPresentationFullScreen;

**Comment by StephanCassel** [comment] 2019-12-27 11:02
Terry
That is a very good finding. I guess **barcode_scan** package will soon be updated.
Thanks to you and to the barcode_scan team.

**Comment by chuanner** [comment] 2020-01-21 05:43
I have the same situation. The page looks ugly. I hope this problem can be fixed as soon as possible~~

**Comment by Stephan-Enoro** [comment] 2020-01-21 09:21
Yes, it would be smashing. barcode_scan is an excellent package and we are depending on it. 
Thanks is advanced.

**Comment by mikhail-karan** [comment] 2020-02-12 17:28
I'm having this issue as well and would love for the pull request that was created to be merged. Thanks!

**Comment by devtronic** [comment] 2020-02-19 20:49
@StephanCassel: Please pull the master branch and check if the issue is still there. PR #167 contains a fix a similar problem

**Closed as completed by devtronic** 2020-02-19 20:49 UTC

**Comment by Stephan-Enoro** [comment] 2020-02-24 07:36
Hi @devtronic  
Sorry about the delay. On journey.
Everything looks very good.
Thanks.
