### ISSUE TITLE
Support stream scan ?

### ISSUE THREAD

**Issue by andiksetyawan** [mintware-de/flutter_barcode_reader#213] opened 2020-04-18 16:59 UTC
Is this plugin possible to scan QR without closing camera / stream scan?

**Comment by devtronic** [comment] 2020-04-18 18:44
This will be possible in a future release. 

Dupe of https://github.com/mintware-de/flutter_barcode_reader/issues/147

**Closed as completed by devtronic** 2020-04-18 18:44 UTC
