### ISSUE TITLE
Errors on build after cloud_firestore upgrade to 0.9.0

### ISSUE THREAD

**Issue by yostrokon** [mintware-de/flutter_barcode_reader#74] opened 2019-02-04 12:11 UTC
After upgrade to 0.9.0 have these errors on build

e: /home/yourii/flutter/.pub-cache/hosted/pub.dartlang.org/barcode_scan-0.0.8/android/src/main/kotlin/com/apptreesoftware/barcodescan/BarcodeScannerActivity.kt: (8, 31): Unresolved reference: ActivityCompat
e: /home/yourii/flutter/.pub-cache/hosted/pub.dartlang.org/barcode_scan-0.0.8/android/src/main/kotlin/com/apptreesoftware/barcodescan/BarcodeScannerActivity.kt: (9, 27): Unresolved reference: content
e: /home/yourii/flutter/.pub-cache/hosted/pub.dartlang.org/barcode_scan-0.0.8/android/src/main/kotlin/com/apptreesoftware/barcodescan/BarcodeScannerActivity.kt: (86, 13): Unresolved reference: ContextCompat
e: /home/yourii/flutter/.pub-cache/hosted/pub.dartlang.org/barcode_scan-0.0.8/android/src/main/kotlin/com/apptreesoftware/barcodescan/BarcodeScannerActivity.kt: (89, 13): Unresolved reference: ActivityCompat

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':barcode_scan:compileDebugKotlin'.

**Comment by matthewtsmith** [comment] 2019-02-08 14:22
Duplicate of #71

**Closed as completed by matthewtsmith** 2019-02-08 14:22 UTC
