### ISSUE TITLE
Android uses a low resolution

### ISSUE THREAD

**Issue by bhammer88** [mintware-de/flutter_barcode_reader#46] opened 2018-09-05 07:03 UTC
Seems like android version defaults to a low resolution for Samsung galaxy tab s2

**Comment by bhammer88** [comment] 2018-09-06 02:45
![screenshot_20180906-103808 1](https://user-images.githubusercontent.com/23393743/45131932-ab90d400-b1c1-11e8-8ee5-dd130d9a8a9b.png)
![screenshot_20180906-103828 1](https://user-images.githubusercontent.com/23393743/45131960-bb101d00-b1c1-11e8-8b30-7b1dd5c8c112.png)

here is an example of the flutter barcode vs dm77 barcode for comparison

**Comment by tdespoulain** [comment] 2018-09-16 20:36
Same thing on Huawei p10 lite. Very low resolution, unable to scan anything

**Comment by edersohe** [comment] 2018-10-15 05:11
Same thing with Huawei P9

**Comment by vuchl** [comment] 2018-10-31 13:12
Here is a reason at least. Still no clue how to work around that: https://github.com/dm77/barcodescanner#advanced-usage

**Comment by matthewtsmith** [comment] 2018-11-02 17:29
Duplicate of https://github.com/apptreesoftware/flutter_barcode_reader/issues/53

**Closed as completed** 2018-11-02 17:29 UTC
