### ISSUE TITLE
The scanning doesn't end

### ISSUE THREAD

**Issue by sanuzzi** [mintware-de/flutter_barcode_reader#218] opened 2020-04-22 03:22 UTC
The following code opens the camera, detects the QR code on an image, and closes the camera. But the result is never returned.

The button:
```
RaisedButton(
  child: Text("Read QR!"),
  onPressed: readQr,
)
```
And a function, like in the documentation:
```
void readQr() async {
  var result= await BarcodeScanner.scan();
  print(result.type);
  print(result.rawContent);
  print(result.format);
  print(result.formatNote);
}
```

These are the logs, between the button clicked and the QR code "read", with the camera turned off again:
```
W/ActivityThread(29505): handleWindowVisibility: no activity for token android.os.BinderProxy@b867015
D/PhoneWindow(29505): forceLight changed to true [] from com.android.internal.policy.PhoneWindow.updateForceLightNavigationBar:4238 com.android.internal.policy.DecorView.updateColorViews:1490 com.android.internal.policy.PhoneWindow.dispatchWindowAttributesChanged:3216 android.view.Window.setFlags:1148 com.android.internal.policy.PhoneWindow.generateLayout:2444 
I/MultiWindowDecorSupport(29505): updateCaptionType >> DecorView@1a1d2b8[], isFloating: false, isApplication: true, hasWindowDecorCaption: false, hasWindowControllerCallback: true
D/MultiWindowDecorSupport(29505): setCaptionType = 0, DecorView = DecorView@1a1d2b8[]
D/ViewRootImpl@d918e7[BarcodeScannerActivity](29505): setView = com.android.internal.policy.DecorView@1a1d2b8 TM=true MM=false
D/ViewRootImpl@d918e7[BarcodeScannerActivity](29505): Relayout returned: old=(0,0,1080,2340) new=(0,0,810,1755) req=(1080,2340)0 dur=7 res=0x7 s={true 482644828160} ch=true
D/OpenGLRenderer(29505): createReliableSurface : 0x6f43158040, 0x705fdfa000
I/mali_winsys(29505): new_window_surface() [810x1755] return: 0x3000
D/ViewRootImpl@cd8c87c[MainActivity](29505): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager(29505): prepareNavigationBarInfo() DecorView@b93c938[MainActivity]
D/InputMethodManager(29505): getNavigationBarColor() -855310
D/SurfaceView(29505): onWindowVisibilityChanged(0) true me.dm7.barcodescanner.core.CameraPreview{7976732 V.E...... ......I. 0,0-0,0} of ViewRootImpl@d918e7[BarcodeScannerActivity]
V/CameraPreview(29505): Cancelling autofocus
D/ViewRootImpl@d918e7[BarcodeScannerActivity](29505): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(29505): prepareNavigationBarInfo() DecorView@1a1d2b8[BarcodeScannerActivity]
D/InputMethodManager(29505): getNavigationBarColor() -855310
D/InputMethodManager(29505): prepareNavigationBarInfo() DecorView@1a1d2b8[BarcodeScannerActivity]
D/InputMethodManager(29505): getNavigationBarColor() -855310
V/InputMethodManager(29505): Starting input: tba=com.sanuzzi.truth_or_dare ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(29505): startInputInner - Id : 0
I/InputMethodManager(29505): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(29505): Input channel destroyed: 'ClientS', fd=103
D/ViewRootImpl@d918e7[BarcodeScannerActivity](29505): Relayout returned: old=(0,0,810,1755) new=(0,0,810,1755) req=(810,1755)0 dur=5 res=0x1 s={true 482644828160} ch=false
D/SurfaceView(29505): surfaceCreated 1 #8 me.dm7.barcodescanner.core.CameraPreview{7976732 V.E...... ......ID 0,0-810,1488}
D/SurfaceView(29505): surfaceChanged (810,1488) 1 #8 me.dm7.barcodescanner.core.CameraPreview{7976732 V.E...... ......ID 0,0-810,1488}
D/ViewRootImpl@d918e7[BarcodeScannerActivity](29505): MSG_RESIZED: frame=(0,0,810,1755) ci=(0,62,0,95) vi=(0,62,0,95) or=1
D/SurfaceView(29505): surfaceChanged (837,1488) 1 #5 me.dm7.barcodescanner.core.CameraPreview{7976732 V.E...... ......ID 0,0-837,1488}
D/SurfaceView(29505): onWindowVisibilityChanged(8) false io.flutter.view.FlutterView{7341fbd VFE...... ........ 0,0-810,1660} of ViewRootImpl@cd8c87c[MainActivity]
D/SurfaceView(29505): surfaceDestroyed callback.size 1 #2 io.flutter.view.FlutterView{7341fbd VFE...... ........ 0,0-810,1660}
I/mali_egl(29505): eglDestroySurface() in
I/mali_winsys(29505): delete_surface() [810x1660] return
I/mali_egl(29505): eglDestroySurface() out
W/libEGL  (29505): EGLNativeWindowType 0x6fca638010 disconnect failed
D/SurfaceView(29505): remove() io.flutter.view.FlutterView{7341fbd VFE...... ........ 0,0-810,1660} Surface(name=SurfaceView - com.sanuzzi.truth_or_dare/com.sanuzzi.truth_or_dare.MainActivity@7341fbd@5)/@0x6ad7e00
I/mali_egl(29505): eglDestroySurface() in
I/mali_winsys(29505): delete_surface() [810x1755] return
I/mali_egl(29505): eglDestroySurface() out
W/libEGL  (29505): EGLNativeWindowType 0x6f431573d0 disconnect failed
D/ViewRootImpl@cd8c87c[MainActivity](29505): Relayout returned: old=(0,0,810,1755) new=(0,0,810,1755) req=(810,1755)8 dur=14 res=0x5 s={false 0} ch=true
D/ViewRootImpl@cd8c87c[MainActivity](29505): stopped(true) old=false
D/SurfaceView(29505): windowStopped(true) false io.flutter.view.FlutterView{7341fbd VFE...... ........ 0,0-810,1660} of ViewRootImpl@cd8c87c[MainActivity]
D/ViewRootImpl@cd8c87c[MainActivity](29505): stopped(false) old=true
D/SurfaceView(29505): windowStopped(false) false io.flutter.view.FlutterView{7341fbd VFE...... ........ 0,0-810,1660} of ViewRootImpl@cd8c87c[MainActivity]
D/ViewRootImpl@cd8c87c[MainActivity](29505): stopped(false) old=false
D/SurfaceView(29505): onWindowVisibilityChanged(0) true io.flutter.view.FlutterView{7341fbd VFE...... ........ 0,0-810,1660} of ViewRootImpl@cd8c87c[MainActivity]
D/ViewRootImpl@cd8c87c[MainActivity](29505): Relayout returned: old=(0,0,810,1755) new=(0,0,810,1755) req=(810,1755)0 dur=7 res=0x7 s={true 478555598848} ch=true
D/OpenGLRenderer(29505): createReliableSurface : 0x6f431573c0, 0x6f6c22f000
I/mali_winsys(29505): new_window_surface() [810x1755] return: 0x3000
D/SurfaceView(29505): surfaceCreated 1 #8 io.flutter.view.FlutterView{7341fbd VFE...... ........ 0,0-810,1660}
I/mali_winsys(29505): new_window_surface() [810x1660] return: 0x3000
D/SurfaceView(29505): surfaceChanged (810,1660) 1 #8 io.flutter.view.FlutterView{7341fbd VFE...... ........ 0,0-810,1660}
D/ViewRootImpl@d918e7[BarcodeScannerActivity](29505): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager(29505): prepareNavigationBarInfo() DecorView@1a1d2b8[BarcodeScannerActivity]
D/InputMethodManager(29505): getNavigationBarColor() -855310
D/ViewRootImpl@cd8c87c[MainActivity](29505): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(29505): prepareNavigationBarInfo() DecorView@b93c938[MainActivity]
D/InputMethodManager(29505): getNavigationBarColor() -855310
D/InputMethodManager(29505): prepareNavigationBarInfo() DecorView@b93c938[MainActivity]
D/InputMethodManager(29505): getNavigationBarColor() -855310
V/InputMethodManager(29505): Starting input: tba=com.sanuzzi.truth_or_dare ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(29505): startInputInner - Id : 0
I/InputMethodManager(29505): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(29505): Input channel destroyed: 'ClientS', fd=115
D/SurfaceView(29505): onWindowVisibilityChanged(8) false me.dm7.barcodescanner.core.CameraPreview{7976732 V.E...... ........ 0,0-837,1488} of ViewRootImpl@d918e7[BarcodeScannerActivity]
D/SurfaceView(29505): surfaceDestroyed callback.size 0 #2 me.dm7.barcodescanner.core.CameraPreview{7976732 V.E...... ........ 0,0-837,1488}
D/SurfaceView(29505): remove() me.dm7.barcodescanner.core.CameraPreview{7976732 V.E...... ........ 0,0-837,1488} Surface(name=SurfaceView - com.sanuzzi.truth_or_dare/de.mintware.barcode_scan.BarcodeScannerActivity@7976732@0)/@0xf945c83
I/mali_egl(29505): eglDestroySurface() in
I/mali_winsys(29505): delete_surface() [810x1755] return
I/mali_egl(29505): eglDestroySurface() out
W/libEGL  (29505): EGLNativeWindowType 0x6f43158050 disconnect failed
D/ViewRootImpl@d918e7[BarcodeScannerActivity](29505): Relayout returned: old=(0,0,810,1755) new=(0,0,810,1755) req=(810,1755)8 dur=14 res=0x5 s={false 0} ch=true
D/ViewRootImpl@d918e7[BarcodeScannerActivity](29505): stopped(true) old=false
D/SurfaceView(29505): windowStopped(true) false me.dm7.barcodescanner.core.CameraPreview{7976732 V.E...... ........ 0,0-837,1488} of ViewRootImpl@d918e7[BarcodeScannerActivity]
D/ViewRootImpl@d918e7[BarcodeScannerActivity](29505): dispatchDetachedFromWindow
D/InputTransport(29505): Input channel destroyed: 'e8233c2', fd=107
```

Apparently, this line of the package never returns:
`var buffer = await _channel.invokeMethod('scan', config?.writeToBuffer());`

Flutter doctor output:
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [VersiÃ³n 10.0.18362.476], locale es-AR)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
[√] VS Code, 64-bit edition (version 1.41.1)

Device: Samsung A50.

**Comment by devtronic** [comment] 2020-04-22 07:38
Dupe of https://github.com/mintware-de/flutter_barcode_reader/issues/217

**Closed as completed by devtronic** 2020-04-22 07:38 UTC

**Comment by sanuzzi** [comment] 2020-04-22 21:10
OK! I didn't enter on that issue because it says "IOS".
@devtronic can you rename the other one?
