### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by daveparks23** [mintware-de/flutter_barcode_reader#234] opened 2020-05-06 21:43 UTC
**Describe the bug**
Android only.  iOS works fine.  The scan does not return anything. 

**To Reproduce**
I trigger the scan function.  The camera starts up and works fine.  Once the barcode has been read the app returns to the screen where the data should appear.  And there is no data.  The code after 
  ```
ScanResult result = await BarcodeScanner.scan(options: options);
setState(() => scanResult = result);
print('Gotaresultforbarcode');
```
The print never occurs in the console.

**Expected behavior**
Scan a barcode or qr code and get a result.

**Environment (please complete the following information):**

Android
LG Stylo 4

 - Version of `barcode_scan` 3.0
 - Output of `flutter --version`: 
```
Flutter 1.14.6 • channel beta • https://github.com/flutter/flutter.git
Framework • revision fabeb2a16f (3 months ago) • 2020-01-28 07:56:51 -0800
Engine • revision c4229bfbba
Tools • Dart 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)
```

```
Future<String> _getBarcode() async {
    print('Get Barcode Started');
    try {
       var options = ScanOptions(
        strings: {
          "cancel": 'Cancel',
          "flash_on": 'Flash',
          "flash_off": 'Flash Off',
        },);
      ScanResult result = await BarcodeScanner.scan(options: options);
      setState(() => scanResult = result);
     print('Gotaresultforbarcode');
     return result.rawContent;
    } on PlatformException catch (e) {
      var result = ScanResult(
        type: ResultType.Error,
        format: BarcodeFormat.unknown,
      );

      if (e.code == BarcodeScanner.cameraAccessDenied) {
        setState(() {
          result.rawContent = 'The user did not grant the camera permission!';
        });
       
      } else {
        result.rawContent = 'Unknown error: $e';
      }
      setState(() {
        scanResult = result;
      });
      return result.rawContent;
    }   
  }
```

**Additional context**

Works on iOS.  This bug only occurs on Android.  
I cannot reproduce when using the example app.
Thanks for any help.

**Comment by devtronic** [comment] 2020-05-07 07:45
Not a bug. Dupe of #227

**Closed as completed by devtronic** 2020-05-07 07:45 UTC

**Comment by daveparks23** [comment] 2020-05-07 16:39
> Not a bug. Dupe of #227

Thank you for your help!  #227 Got me going in the right direction!  Problem resolved!
