### ISSUE TITLE
[Feature Request] Continuous Scan Mode

### ISSUE THREAD

**Issue by david-kalbermatten** [mintware-de/flutter_barcode_reader#295] opened 2020-09-30 16:39 UTC
**Is your feature request related to a problem? Please describe.**
I'm building a contact tracing app that uses barcodes (hence why I'm here :D). The issue I'm facing is my need to use the scanner continuously. 

**Describe the solution you'd like**
I'd like there to be an option where the scanner can be opened and used continuously i.e. without closing the scanner in between scans.

**Describe alternatives you've considered**
Right now, I'm closing and opening the scanner and reopen it after each scan.

**Additional context**
Another thing I noticed is the scanner not invoking a wakelock to keep the screen on while scanning. I don't know whether or not this deserves a separate issue/feature request. I can kind of circumvent the issue right for now, since the scanner closes every so often and re-engages the wakelock, however, if you consider adding the continuous mode you'd have to also address the wakelock issue.

**Comment by devtronic** [comment] 2020-10-01 08:19
Dupe of https://github.com/mintware-de/flutter_barcode_reader/issues/147

**Closed as completed by devtronic** 2020-10-01 08:19 UTC
Labels: Feature
